### ISSUE TITLE
Emitter (Layer) misses a link

### ISSUE THREAD

**Issue by velcrome** [letmp/dx11-particles#1]
just downloaded a new version with vpm

Emitter (DX11.Particles Layer) has a missing link, that prevents it from functioning correctly.
![image](https://cloud.githubusercontent.com/assets/280537/25314270/446db99c-2841-11e7-920a-c5b607895dc5.png)

**Comment by velcrome** [comment]
related to this: it would be nice to have an output pin with the internal texture from the module.

**Comment by letmp** [comment]
fixed with latest commit
