### ISSUE TITLE
Disabling emitters kills all their particles

### ISSUE THREAD

**Issue by TobyKLight** [letmp/dx11-particles#10]
Unless this is the intended behaviour?
I recall in previous versions it stopped emitting but existing particles persisted. I could be wrong though.

**Comment by letmp** [comment]
can you please download the latest release and test it?
this commit should fix that problem: https://github.com/letmp/dx11-particles/commit/36f8881e7b2619fa20786c2c4f28ed054cd0f898

**Comment by TobyKLight** [comment]
Solved in latest release thanks!
