### ISSUE TITLE
plugin path issue

### ISSUE THREAD

**Issue by circuitb** [letmp/dx11-particles#12]
https://github.com/letmp/dx11-particles/blob/d85c50be5f6386f8993697e95db149637250fd9e/packs/dx11.particles/nodes/modules/Tools/Camera%20(DX11.Particles.Tools).v4p#L207

ps: also the Fov iobox should be Vector2D

**Comment by letmp** [comment]
fixed with commit [4cb813a](https://github.com/letmp/dx11-particles/commit/4cb813a94113d897a22b5def2be99195ea8e1036)
