### ISSUE TITLE
Incompatibility with dx11-vvvv 1.0.1.13

### ISSUE THREAD

**Issue by velcrome** [letmp/dx11-particles#3]
Cannot connect the output of the multibuffered renderer to any of the provided visualisations like Constant.

**Comment by velcrome** [comment]
to replicate, install latest dx11 version, open Emitter (Dynamic) help patch and disconnect the ParticleSystem node from the Sprite. It is impossible to reconnect again. 

![image](https://cloud.githubusercontent.com/assets/280537/25785611/6e880986-3385-11e7-9159-0ea380ebc63a.png)

had a quick look at the csproj, but could not find anything obvious

**Comment by letmp** [comment]
the particles pack is compiled against the official releases on the vvvv contributions page.

so if you need builds for the latest dx11 version, checkout the sources of dx11.particles, copy the dlls from **vvvv/packs/dx11/core/** to **dx11-particles/src/Dependencies/architecture/** and then compile it. after that you can copy **dx11-particles/packs/dx11-particles** to your vvvv-packs folder and it should work again.

**Comment by velcrome** [comment]
Fair enough, I can accept that. Just keep it in mind as an early warning sign, when vux uploads a new version to vvvv.org

Btw, vvvv-Message was still working, even with the newer dx11-vvvv version. So there must be a way.
I thought it might be the` <SpecificVersion> `flags, but seems, you've used that too...
