### ISSUE TITLE
Importer Chunks Doesnt like Capturing reality PLY's

### ISSUE THREAD

**Issue by catvvvveasel** [letmp/dx11-particles#5]
capturing reality exports PLY with this header

ply
format binary_little_endian 1.0
comment Generated by Capturing Reality 
element vertex 376969
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element face 753870
property list uchar int vertex_indices
end_header

Which the ply importer doesn't like.

**Comment by letmp** [comment]
thanks for the hint.
there is no support for binary ply files at the moment and there wont be in the near future.
I've added an exception that informs about this issue.

meanwhile you can have a look at this page:
https://codeyarns.com/2011/08/20/convert-between-ascii-and-binary-ply-file-formats/
