### ISSUE TITLE
Memory Leak when Resetting

### ISSUE THREAD

**Issue by rmtttt** [letmp/dx11-particles#6]
One year ago there was the same issue. 
Now it seems like a bug in _Renderer (DX11 MultiStructuredBuffer)_ - easy to reproduce with bigger buffer.
vvvv_50beta35.8_x64
dx11.particles_1.0.5_x64
dx11-1.2-x64

**Comment by letmp** [comment]
Can you provide a patch please?

**Comment by rmtttt** [comment]
Here are two patches. On my machine it takes from one to two minutes to start increasing very fast. You can pause LFO to stop it.
[Memory_Leak.zip](https://github.com/letmp/dx11-particles/files/1983449/Memory_Leak.zip)

**Comment by letmp** [comment]
Should be fixed with latest commit

https://github.com/letmp/dx11-particles/commit/3c78b350d58cadcd9bf9ba819c9b6c9d5b928385
