### ISSUE TITLE
Layer emitter pixel grid is broken

### ISSUE THREAD

**Issue by jvolker** [letmp/dx11-particles#9]
Using the layer emitter help patch and swapping the sphere for a fullscreen quad I get the following which is a particle grid with a holey/striped pattern. I would expect a perfect pixel grid instead.

![image](https://user-images.githubusercontent.com/546852/41398746-77019f68-700c-11e8-9c94-556fdda742b7.png)

**Comment by letmp** [comment]
fixed with commit https://github.com/letmp/dx11-particles/commit/065a596edfa02f65091fd2c83b275b174605c019
